version: '3.8'
services:
  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    command: npm run dev
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local
